name: aoc
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h9214b88_0
  - icc_rt=2022.1.0=h6049295_2
  - intel-openmp=2025.0.0=haa95532_1164
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libmpdec=4.0.0=h827c3e9_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py313h0b37514_0
  - mkl_fft=2.1.1=py313hbc2a22c_0
  - mkl_random=1.3.0=py313h42c1672_0
  - numpy=2.3.5=py313h050da96_0
  - numpy-base=2.3.5=py313h1e017a8_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.13.11=h260b955_100_cp313
  - python_abi=3.13=3_cp313
  - scipy=1.16.3=py313hbd6d557_0
  - setuptools=80.9.0=py313haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py313haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - immutabledict==4.2.2
      - ortools==9.14.6206
      - pandas==2.3.3
      - protobuf==6.31.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - six==1.17.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
prefix: C:\Users\n8\miniconda3\envs\aoc
